<?php
/*
Template Name:single-pentry_test
*/?>

<!DOCTYPE html>
<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"><title>http://www.hontoyutari.com/project/entry/post-632/</title><link rel="stylesheet" type="text/css" href="demo_pentry_files/viewsource.css"></head><body contextmenu="actions" id="viewsource" class="wrap highlight" style="-moz-tab-size: 4"><pre id="line1"><span></span><span class="doctype">&lt;!doctype html&gt;</span><span>
<span id="line2"></span></span><span>&lt;<span class="start-tag">html</span>&gt;</span><span>
<span id="line3"></span>
<span id="line4"></span></span><span>&lt;<span class="start-tag">head</span>&gt;</span><span>
<span id="line5"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">http-equiv</span>="<a class="attribute-value">X-UA-Compatible</a>" <span class="attribute-name">content</span>="<a class="attribute-value">IE=Edge</a>"&gt;</span><span>
<span id="line6"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">charset</span>="<a class="attribute-value">utf-8</a>"&gt;</span><span>
<span id="line7"></span></span><span>&lt;<span class="start-tag">title</span>&gt;</span><span>
<span id="line8"></span>笠間焼のおまもりブローチ｜プロジェクト｜本とゆたり</span><span>&lt;/<span class="end-tag">title</span>&gt;</span><span>
<span id="line9"></span>
<span id="line10"></span></span><span class="comment">&lt;!--メタタグここから--&gt;</span><span>
<span id="line11"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>="<a class="attribute-value">description</a>" <span class="attribute-name">content</span>="<a class="attribute-value">笠間焼のおまもりブローチ｜プロジェクト｜本とゆたり</a>"&gt;</span><span>
<span id="line12"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>="<a class="attribute-value">keywords</a>" <span class="attribute-name">content</span>="<a class="attribute-value">笠間焼のおまもりブローチ｜プロジェクト｜本とゆたり</a>"&gt;</span><span>
<span id="line13"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>="<a class="attribute-value">viewport</a>" <span class="attribute-name">content</span>="<a class="attribute-value">width=1515</a>"&gt;</span><span>
<span id="line14"></span></span><span class="comment">&lt;!--メタタグここまで--&gt;</span><span>
<span id="line15"></span>
<span id="line16"></span></span><span class="comment">&lt;!--OGPここから--&gt;</span><span>
<span id="line17"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">property</span>="<a class="attribute-value">og:title</a>" <span class="attribute-name">content</span>="<a class="attribute-value">笠間焼のおまもりブローチ｜プロジェクト｜本とゆたり</a>"&gt;</span><span>
<span id="line18"></span>
<span id="line19"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">property</span>="<a class="attribute-value">og:url</a>" <span class="attribute-name">content</span>="<a class="attribute-value">http://www.hontoyutari.com/project/entry/post-632/</a>"&gt;</span><span>
<span id="line20"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">property</span>="<a class="attribute-value">og:image</a>" <span class="attribute-name">content</span>="<a class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/07/kasama02_01.jpg</a>"&gt;</span><span>
<span id="line21"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">property</span>="<a class="attribute-value">og:type</a>" <span class="attribute-name">content</span>="<a class="attribute-value">article</a>"&gt;</span><span>
<span id="line22"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">property</span>="<a class="attribute-value">og:site_name</a>" <span class="attribute-name">content</span>="<a class="attribute-value">本とゆたり</a>"&gt;</span><span>
<span id="line23"></span>
<span id="line24"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">property</span>="<a class="attribute-value">og:description</a>" <span class="attribute-name">content</span>="<a class="attribute-value"></a>" <span>/</span>&gt;</span><span>
<span id="line25"></span></span><span class="comment">&lt;!--OGPここまで--&gt;</span><span>
<span id="line26"></span>
<span id="line27"></span></span><span class="comment">&lt;!--favicon--&gt;</span><span>
<span id="line28"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">apple-touch-icon</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">57x57</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-57x57.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-57x57.png</a>"&gt;</span><span>
<span id="line29"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">apple-touch-icon</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">60x60</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-60x60.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-60x60.png</a>"&gt;</span><span>
<span id="line30"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">apple-touch-icon</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">72x72</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-72x72.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-72x72.png</a>"&gt;</span><span>
<span id="line31"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">apple-touch-icon</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">76x76</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-76x76.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-76x76.png</a>"&gt;</span><span>
<span id="line32"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">apple-touch-icon</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">114x114</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-114x114.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-114x114.png</a>"&gt;</span><span>
<span id="line33"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">apple-touch-icon</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">120x120</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-120x120.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-120x120.png</a>"&gt;</span><span>
<span id="line34"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">apple-touch-icon</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">144x144</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-144x144.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-144x144.png</a>"&gt;</span><span>
<span id="line35"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">apple-touch-icon</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">152x152</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-152x152.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-152x152.png</a>"&gt;</span><span>
<span id="line36"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">apple-touch-icon</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">180x180</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-180x180.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/apple-touch-icon-180x180.png</a>"&gt;</span><span>
<span id="line37"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">icon</a>" <span class="attribute-name">type</span>="<a class="attribute-value">image/png</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/favicon-32x32.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/favicon-32x32.png</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">32x32</a>"&gt;</span><span>
<span id="line38"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">icon</a>" <span class="attribute-name">type</span>="<a class="attribute-value">image/png</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/android-chrome-192x192.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/android-chrome-192x192.png</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">192x192</a>"&gt;</span><span>
<span id="line39"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">icon</a>" <span class="attribute-name">type</span>="<a class="attribute-value">image/png</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/favicon-96x96.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/favicon-96x96.png</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">96x96</a>"&gt;</span><span>
<span id="line40"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">icon</a>" <span class="attribute-name">type</span>="<a class="attribute-value">image/png</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/favicon-16x16.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/favicon-16x16.png</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">16x16</a>"&gt;</span><span>
<span id="line41"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">manifest</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/manifest.json" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/manifest.json</a>"&gt;</span><span>
<span id="line42"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">mask-icon</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/safari-pinned-tab.svg" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/safari-pinned-tab.svg</a>" <span class="attribute-name">color</span>="<a class="attribute-value">#da5443</a>"&gt;</span><span>
<span id="line43"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>="<a class="attribute-value">msapplication-TileColor</a>" <span class="attribute-name">content</span>="<a class="attribute-value">#ffffff</a>"&gt;</span><span>
<span id="line44"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>="<a class="attribute-value">msapplication-TileImage</a>" <span class="attribute-name">content</span>="<a class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/favicons/mstile-144x144.png</a>"&gt;</span><span>
<span id="line45"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>="<a class="attribute-value">theme-color</a>" <span class="attribute-name">content</span>="<a class="attribute-value">#ffffff</a>"&gt;</span><span>
<span id="line46"></span></span><span class="comment">&lt;!--favicon--&gt;</span><span>
<span id="line47"></span>
<span id="line48"></span></span><span class="comment">&lt;!--cssここから--&gt;</span><span>
<span id="line49"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">stylesheet</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/css/css01.css" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/css/css01.css</a>"&gt;</span><span>
<span id="line50"></span>
<span id="line51"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">stylesheet</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-project/css/project_common.css" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-project/css/project_common.css</a>"&gt;</span><span>
<span id="line52"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">stylesheet</a>" <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-project/css/project.css" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-project/css/project.css</a>"&gt;</span><span>
<span id="line53"></span></span><span class="comment">&lt;!--cssここまで--&gt;</span><span>
<span id="line54"></span>
<span id="line55"></span></span><span class="comment">&lt;!--スクリプトここから--&gt;</span><span>
<span id="line56"></span></span><span class="comment">&lt;!--[if lt IE 9]&gt;&lt;script src="../common/js/IE9.js"&gt;&lt;/script&gt;&lt;![endif]--&gt;</span><span>
<span id="line57"></span></span><span class="comment">&lt;!--[if lt IE 8]&gt;&lt;script src="../common/js/selectivizr-1.0.2.js"&gt;&lt;/script&gt;&lt;![endif]--&gt;</span><span>
<span id="line58"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/smartRollover.js" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/smartRollover.js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line59"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/jquery-1.9.1.min.js" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/jquery-1.9.1.min.js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line60"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/jquery.placeholder.js" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/jquery.placeholder.js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line61"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/jquery.customSelect-0.5.1.js" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/jquery.customSelect-0.5.1.js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line62"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/page_top.js" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/page_top.js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line63"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/fixHeight.mod.js" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/fixHeight.mod.js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line64"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/jquery.sidebar.fix.js" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/jquery.sidebar.fix.js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line65"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/import_script_pc.js" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/js/import_script_pc.js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line66"></span></span><span class="comment">&lt;!--スクリプトここまで--&gt;</span><span>
<span id="line67"></span></span><span class="comment">&lt;!--J Query'single-galleryGallery'用スクリプト--&gt;</span><span>
<span id="line68"></span></span><span class="comment">&lt;!--J Query'single-gallery'用スクリプト--&gt;</span><span>
<span id="line69"></span></span><span>&lt;/<span class="end-tag">head</span>&gt;</span><span>
<span id="line70"></span>
<span id="line71"></span></span><span>&lt;<span class="start-tag">body</span>&gt;</span><span>
<span id="line72"></span></span><span>&lt;<span class="start-tag">script</span>&gt;</span><span>
<span id="line73"></span>  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
<span id="line74"></span>  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
<span id="line75"></span>  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
<span id="line76"></span>  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
<span id="line77"></span>
<span id="line78"></span>  ga('create', 'UA-1948421-52', 'auto');
<span id="line79"></span>  ga('send', 'pageview');
<span id="line80"></span>
<span id="line81"></span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line82"></span></span><span class="comment">&lt;!--ラッパーここから--&gt;</span><span>
<span id="line83"></span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">wrapper</a>"&gt;</span><span>
<span id="line84"></span>
<span id="line85"></span></span><span class="comment">&lt;!--サイドバーここから--&gt;</span><span>
<span id="line86"></span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">sidebar</a>"&gt;</span><span>
<span id="line87"></span>  </span><span>&lt;<span class="start-tag">aside</span>&gt;</span><span>
<span id="line88"></span>
<span id="line89"></span>    </span><span class="comment">&lt;!--サイドバーコンテンツここから--&gt;</span><span>
<span id="line90"></span>    </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">sidebar_contents</a>"&gt;</span><span>
<span id="line91"></span>
<span id="line92"></span>      </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">site_logo</a>"&gt;</span><span>
<span id="line93"></span>        </span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/" class="attribute-value">http://www.hontoyutari.com/</a>"&gt;</span><span>
<span id="line94"></span>          </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/logo.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/logo.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">142</a>" <span class="attribute-name">height</span>="<a class="attribute-value">265</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">本とゆたり　BOOK AND YUTARI</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line95"></span>      </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>          </span><span class="comment">&lt;!--グローバルナビここから--&gt;</span><span>
<span id="line96"></span>        </span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">id</span>="<a class="attribute-value">g_nav</a>"&gt;</span><span>
<span id="line97"></span>          </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/book/" class="attribute-value">http://www.hontoyutari.com/book/</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/nav-book_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/nav-book_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">114</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">BOOK</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line98"></span>          </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/goods/" class="attribute-value">http://www.hontoyutari.com/goods/</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/nav-goods_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/nav-goods_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">114</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">GOODS</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line99"></span>          </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/project/" class="attribute-value">http://www.hontoyutari.com/project/</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/nav-project_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/nav-project_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">114</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">PROJECT</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line100"></span>          </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/shop/" class="attribute-value">http://www.hontoyutari.com/shop/</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/nav-shop_list_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/nav-shop_list_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">114</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">SHOP LIST</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line101"></span>          </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/about/" class="attribute-value">http://www.hontoyutari.com/about/</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/nav-about_us_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/nav-about_us_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">114</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">ABOUT US</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line102"></span>          </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/info/" class="attribute-value">http://www.hontoyutari.com/info/</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/nav-info_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/nav-info_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">143</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">INFOMATION</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line103"></span>          </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:https://hontoyutari.stores.jp/" class="attribute-value">https://hontoyutari.stores.jp/</a>" <span class="attribute-name">target</span>="<a class="attribute-value">_blank</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/btn-online_store_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/btn-online_store_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">168</a>" <span class="attribute-name">height</span>="<a class="attribute-value">51</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">ONLINE STORE</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line104"></span>        </span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>
<span id="line105"></span>        </span><span class="comment">&lt;!--グローバルナビここまで--&gt;</span><span>
<span id="line106"></span>
<span id="line107"></span>      </span><span class="comment">&lt;!--アイコン各種ここから--&gt;</span><span>
<span id="line108"></span>      </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">yutari_icon</a>"&gt;</span><span>
<span id="line109"></span>        </span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://yutari.jp/" class="attribute-value">http://yutari.jp/</a>" <span class="attribute-name">target</span>="<a class="attribute-value">_blank</a>"&gt;</span><span>
<span id="line110"></span>          </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/icon-yutari.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/sidebar/icon-yutari.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">38</a>" <span class="attribute-name">height</span>="<a class="attribute-value">38</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">ゆたり</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line111"></span>      </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line112"></span>
<span id="line113"></span>      </span><span class="comment">&lt;!--アイコン各種ここまで--&gt;</span><span>
<span id="line114"></span>      </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">copy_right</a>"&gt;</span><span><span class="entity"><span>&amp;</span>copy;</span> 2015 Hon to yutari</span><span>&lt;<span class="start-tag">br</span>&gt;</span><span>
<span id="line115"></span>        All Rights Reserved.</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line116"></span>      </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line117"></span>  </span><span class="comment">&lt;!--サイドバーコンテンツここまで--&gt;</span><span>
<span id="line118"></span>  </span><span>&lt;/<span class="end-tag">aside</span>&gt;</span><span>
<span id="line119"></span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line120"></span></span><span class="comment">&lt;!--サイドバーここまで--&gt;</span><span>
<span id="line121"></span>
<span id="line122"></span></span><span class="comment">&lt;!--コンテナーここから--&gt;</span><span>
<span id="line123"></span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">container</a>"&gt;</span><span>
<span id="line124"></span>
<span id="line125"></span>  </span><span class="comment">&lt;!--ヘッダー帯画像--&gt;</span><span>
<span id="line126"></span>  </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">page_ttl</a>"&gt;</span><span>
<span id="line127"></span>    </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-project/image/img-page_header_project.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-project/image/img-page_header_project.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">1300</a>" <span class="attribute-name">height</span>="<a class="attribute-value">195</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">PROJECT</a>"&gt;</span><span>
<span id="line128"></span>  </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line129"></span>  </span><span class="comment">&lt;!--ヘッダー帯画像--&gt;</span><span>
<span id="line130"></span>
<span id="line131"></span>  </span><span class="comment">&lt;!--メインここから--&gt;</span><span>
<span id="line132"></span>  </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">project_common</a>"&gt;</span><span>
<span id="line133"></span>    </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">project</a>" <span class="attribute-name">class</span>="<a class="attribute-value">main</a>"&gt;</span><span>
<span id="line134"></span>      </span><span>&lt;<span class="start-tag">article</span>&gt;</span><span>
<span id="line135"></span>        </span><span>&lt;<span class="start-tag">section</span>&gt;</span><span>
<span id="line136"></span>          </span><span class="comment">&lt;!--コンテンツ（カラム版）ここから--&gt;</span><span>
<span id="line137"></span>          </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">content_outline</a>"&gt;</span><span>
<span id="line138"></span>            </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">contents_column</a>"&gt;</span><span>
<span id="line139"></span>
<span id="line140"></span>                              </span><span class="comment">&lt;!--左ブロックここから--&gt;</span><span>
<span id="line141"></span>                  </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">left_block</a>"&gt;</span><span>
<span id="line142"></span>                    </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">left_block_inner</a>"&gt;</span><span>
<span id="line143"></span>
<span id="line144"></span>                      </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">project_exp</a>"&gt;</span><span>
<span id="line145"></span>                          </span><span class="comment">&lt;!--カスタム分類のスラッグを取得--&gt;</span><span>
<span id="line146"></span>                                                                              </span><span class="comment">&lt;!--&lt;img

src="http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-project/image/index/project03.png"
 alt=""&gt;--&gt;</span><span>
<span id="line147"></span>
<span id="line148"></span>                      </span><span>&lt;<span class="start-tag">h1</span>&gt;</span><span>気軽に身につけて</span><span>&lt;<span class="start-tag">br</span> <span>/</span>&gt;</span><span>
<span id="line149"></span>ちょっと特別な1日に</span><span>&lt;/<span class="end-tag">h1</span>&gt;</span><span>
<span id="line150"></span>                      </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">address</a>"&gt;</span><span>
<span id="line151"></span>                                                茨城県
<span id="line152"></span>                                                笠間市                      </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line153"></span>                    </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line154"></span>
<span id="line155"></span>                  </span><span>&lt;<span class="start-tag">h2</span>&gt;</span><span>かさまのうつわ掲載作家のブローチ企画</span><span>&lt;/<span class="end-tag">h2</span>&gt;</span><span>
<span id="line156"></span>
<span id="line157"></span>                    </span><span>&lt;<span class="start-tag">p</span>&gt;</span><span>いつもと少し雰囲気を変えて出かけたくなる商品「笠間焼のお守りブローチ」。</span><span>&lt;<span class="start-tag">br</span> <span>/</span>&gt;</span><span>
<span id="line158"></span>旅先のお守りにブローチを身につけ、普段とは違う特別な時間をご提案。</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line159"></span></span><span>&lt;<span class="start-tag">p</span>&gt;</span><span>今回は「かさまのうつわ」掲載作家の阿部 慎太朗さん、松本 良太さん、長嶺 憲幸さん、馬目 隆広さん、CRAFT BORO×BOROさんにご協力していただきました。作家さんそれぞれの特徴が出ているブローチです。ぜひ自分のお気に入りを探してみてください。</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line160"></span></span><span>&lt;<span class="start-tag">p</span>&gt;</span><span><span class="entity"><span>&amp;</span>nbsp;</span></span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line161"></span></span><span>&lt;<span class="start-tag">p</span>&gt;</span><span></span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">style</span>="<a class="attribute-value">color: #ff0000;</a>"&gt;</span><span>【商品の購入について】</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;<span class="start-tag">br</span> <span>/</span>&gt;</span><span>
<span id="line162"></span>この商品は未来屋書店つくば、土浦店で開催中の『本とゆたりのブックフェア』での先行発売商品です。2017年1月よりオンライン販売を開始いたします。商品情報は随時更新いたしますので、もうしばらくお待ちください。</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line163"></span></span><span>&lt;<span class="start-tag">p</span>&gt;</span><span><span class="entity"><span>&amp;</span>nbsp;</span></span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line164"></span></span><span>&lt;<span class="start-tag">p</span>&gt;</span><span></span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">class</span>="<a class="attribute-value">alignnone size-full wp-image-638</a>" <span class="attribute-name">src</span>="<a href="view-source:http://hontoyutari.com/wpkanri/wp-content/uploads/2016/07/kasama02_02.jpg" class="attribute-value">http://hontoyutari.com/wpkanri/wp-content/uploads/2016/07/kasama02_02.jpg</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">kasama02_02</a>" <span class="attribute-name">width</span>="<a class="attribute-value">560</a>" <span class="attribute-name">height</span>="<a class="attribute-value">315</a>" <span class="attribute-name">srcset</span>="<a class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/07/kasama02_02.jpg
 560w,
http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/07/kasama02_02-280x158.jpg
 280w,
http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/07/kasama02_02-350x197.jpg
 350w</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">(max-width: 560px) 100vw, 560px</a>" <span>/</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line165"></span>
<span id="line166"></span>                    </span><span class="comment">&lt;!--ゆたりの記事へのリンクボタン--&gt;</span><span>
<span id="line167"></span>                    </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">read_article</a>"&gt;</span><span>
<span id="line168"></span>                                          </span><span class="comment">&lt;!--'p_con_left'に情報がなければこの場所にボタンを表示--&gt;</span><span>
<span id="line169"></span>                                                                                            </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line170"></span>                    </span><span class="comment">&lt;!--ゆたりの記事へのリンクボタン--&gt;</span><span>
<span id="line171"></span>
<span id="line172"></span>                  </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line173"></span>                </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line174"></span>              </span><span class="comment">&lt;!--左ブロックここまで--&gt;</span><span>
<span id="line175"></span>
<span id="line176"></span>
<span id="line177"></span>
<span id="line178"></span>              </span><span class="comment">&lt;!--右ブロックここから--&gt;</span><span>
<span id="line179"></span>              </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">right_block</a>"&gt;</span><span>
<span id="line180"></span>
<span id="line181"></span>                </span><span class="comment">&lt;!--カスタム分類のスラッグを取得--&gt;</span><span>
<span id="line182"></span>
<span id="line183"></span>                </span><span class="comment">&lt;!-- スラッグからページ情報を取得 --&gt;</span><span>
<span id="line184"></span>
<span id="line185"></span>                </span><span class="comment">&lt;!--このプロジェクトについてここから--&gt;</span><span>
<span id="line186"></span>                </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">about_project</a>"&gt;</span><span>
<span id="line187"></span>                  </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">sam</a>"&gt;</span><span>
<span id="line188"></span>                    </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">width</span>="<a class="attribute-value">350</a>" <span class="attribute-name">height</span>="<a class="attribute-value">230</a>" <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/05/P03_index_sam01.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/05/P03_index_sam01.png</a>" <span class="attribute-name">class</span>="<a class="attribute-value">attachment-post-thumbnail size-post-thumbnail wp-post-image</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">P03_index_sam01</a>" <span class="attribute-name">srcset</span>="<a class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/05/P03_index_sam01.png
 350w,
http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/05/P03_index_sam01-280x184.png
 280w</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">(max-width: 350px) 100vw, 350px</a>" <span>/</span>&gt;</span><span>                    </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line189"></span>
<span id="line190"></span>                    </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-project/image/index/project03_s.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-project/image/index/project03_s.png</a>" <span class="attribute-name">alt</span>="<a class="attribute-value"></a>"&gt;</span><span>
<span id="line191"></span>
<span id="line192"></span>                  </span><span>&lt;<span class="start-tag">h3</span>&gt;</span><span>笠間焼プロジェクト</span><span>&lt;/<span class="end-tag">h3</span>&gt;</span><span>
<span id="line193"></span>                  </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">exp</a>"&gt;</span><span>
<span id="line194"></span>                    </span><span>&lt;<span class="start-tag">p</span>&gt;</span><span>
<span id="line195"></span>                      </span><span>&lt;<span class="start-tag">p</span>&gt;</span><span>関
東地方で、栃木県の益子と並ぶ大きな窯業産地として知られる茨城県の笠間。毎年春に開かれる「笠間の陶炎祭（ひまつり）」には何万もの人が県内外から来場
します。多くの人を魅了する笠間焼。器を作る人と使う人、それぞれを紹介する「笠間の器プロジェクト」では、笠間焼の楽しみ方がきっと広がります。</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line196"></span>                  </span><span title="No &quot;p&quot; element in scope but a &quot;p&quot; end tag seen." class="error">&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line197"></span>                  </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line198"></span>                  </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line199"></span>                </span><span class="comment">&lt;!--このプロジェクトについてここまで--&gt;</span><span>
<span id="line200"></span>
<span id="line201"></span>                </span><span class="comment">&lt;!--カテゴリーメニューここから--&gt;</span><span>
<span id="line202"></span>                </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">category_menu</a>" <span class="attribute-name">class</span>="<a class="attribute-value">a-box</a>"&gt;</span><span>
<span id="line203"></span>                  </span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">menu_logo</a>"&gt;</span><span>
<span id="line204"></span>                    </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/contents/logo-project.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/contents/logo-project.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">77</a>" <span class="attribute-name">height</span>="<a class="attribute-value">94</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">PROJECT</a>"<span>/</span>&gt;</span><span>
<span id="line205"></span>                    </span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line206"></span>
<span id="line207"></span>                    </span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>"&gt;</span><span>
<span id="line208"></span>                          $(document).on('click','dt span',function(){
<span id="line209"></span>                          	$(this).parent('dt').next('dd').slideToggle();
<span id="line210"></span>                          	jQuery(this).toggleClass('close');
<span id="line211"></span>                          	if (jQuery(this).hasClass('close')) {
<span id="line212"></span>                          		jQuery(this).text('\u2227');
<span id="line213"></span>                          	} else {
<span id="line214"></span>                          		jQuery(this).text('\u2228');
<span id="line215"></span>                          	}
<span id="line216"></span>                          	return false;
<span id="line217"></span>                          });
<span id="line218"></span>                    </span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line219"></span>
<span id="line220"></span>                      </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">menu_outline</a>"&gt;</span><span>
<span id="line221"></span>
<span id="line222"></span>                                                                                                        </span><span>&lt;<span class="start-tag">dl</span>&gt;</span><span>
<span id="line223"></span>                          	</span><span>&lt;<span class="start-tag">dt</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/project/project01/" class="attribute-value">http://www.hontoyutari.com/project/project01/</a>"&gt;</span><span>01木を植える音楽プロジェクト</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span> </span><span>&lt;<span class="start-tag">span</span>&gt;</span><span><span class="entity"><span>&amp;</span>#8744;</span></span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">dt</span>&gt;</span><span>
<span id="line224"></span>                          	</span><span>&lt;<span class="start-tag">dd</span>&gt;</span><span>
<span id="line225"></span>                          		</span><span>&lt;<span class="start-tag">ul</span>&gt;</span><span>
<span id="line226"></span>                          		                          		</span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/project/entry/post-51/" class="attribute-value">http://www.hontoyutari.com/project/entry/post-51/</a>"&gt;</span><span>日常に寄り添う音楽で、いわきの海岸に「木を植える」</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line227"></span>
<span id="line228"></span>                          		                          		</span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>
<span id="line229"></span>                          	</span><span>&lt;/<span class="end-tag">dd</span>&gt;</span><span>
<span id="line230"></span>                          </span><span>&lt;/<span class="end-tag">dl</span>&gt;</span><span>
<span id="line231"></span>                                                                              </span><span>&lt;<span class="start-tag">dl</span>&gt;</span><span>
<span id="line232"></span>                          	</span><span>&lt;<span class="start-tag">dt</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/project/project02/" class="attribute-value">http://www.hontoyutari.com/project/project02/</a>"&gt;</span><span>02ゆたり文庫プロジェクト</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span> </span><span>&lt;<span class="start-tag">span</span>&gt;</span><span><span class="entity"><span>&amp;</span>#8744;</span></span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">dt</span>&gt;</span><span>
<span id="line233"></span>                          	</span><span>&lt;<span class="start-tag">dd</span>&gt;</span><span>
<span id="line234"></span>                          		</span><span>&lt;<span class="start-tag">ul</span>&gt;</span><span>
<span id="line235"></span>                          		                          		</span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/project/entry/post-448/" class="attribute-value">http://www.hontoyutari.com/project/entry/post-448/</a>"&gt;</span><span>ひとが輝くまちの学校</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line236"></span>
<span id="line237"></span>                          		                          		</span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/project/entry/post-50/" class="attribute-value">http://www.hontoyutari.com/project/entry/post-50/</a>"&gt;</span><span>地方とわたしとつながる世界</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line238"></span>
<span id="line239"></span>                          		                          		</span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>
<span id="line240"></span>                          	</span><span>&lt;/<span class="end-tag">dd</span>&gt;</span><span>
<span id="line241"></span>                          </span><span>&lt;/<span class="end-tag">dl</span>&gt;</span><span>
<span id="line242"></span>                                                                              </span><span>&lt;<span class="start-tag">dl</span>&gt;</span><span>
<span id="line243"></span>                          	</span><span>&lt;<span class="start-tag">dt</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/project/project03/" class="attribute-value">http://www.hontoyutari.com/project/project03/</a>"&gt;</span><span>03笠間焼プロジェクト</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span> </span><span>&lt;<span class="start-tag">span</span>&gt;</span><span><span class="entity"><span>&amp;</span>#8744;</span></span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">dt</span>&gt;</span><span>
<span id="line244"></span>                          	</span><span>&lt;<span class="start-tag">dd</span>&gt;</span><span>
<span id="line245"></span>                          		</span><span>&lt;<span class="start-tag">ul</span>&gt;</span><span>
<span id="line246"></span>                          		                          		</span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/project/entry/post-632/" class="attribute-value">http://www.hontoyutari.com/project/entry/post-632/</a>"&gt;</span><span>笠間焼のおまもりブローチ</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line247"></span>
<span id="line248"></span>                          		                          		</span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/project/entry/post-49/" class="attribute-value">http://www.hontoyutari.com/project/entry/post-49/</a>"&gt;</span><span>作るひと、使うひと　笠間の器プロジェクト</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line249"></span>
<span id="line250"></span>                          		                          		</span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>
<span id="line251"></span>                          	</span><span>&lt;/<span class="end-tag">dd</span>&gt;</span><span>
<span id="line252"></span>                          </span><span>&lt;/<span class="end-tag">dl</span>&gt;</span><span>
<span id="line253"></span>
<span id="line254"></span>                    </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line255"></span>
<span id="line256"></span>                  </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line257"></span>                </span><span class="comment">&lt;!--カテゴリーメニューここまで--&gt;</span><span>
<span id="line258"></span>
<span id="line259"></span>                </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line260"></span>              </span><span class="comment">&lt;!--右ブロックここまで--&gt;</span><span>
<span id="line261"></span>
<span id="line262"></span>        </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line263"></span>      </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line264"></span>    </span><span class="comment">&lt;!--コンテンツ（カラム版）ここまで--&gt;</span><span>
<span id="line265"></span>
<span id="line266"></span>          </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">break_img</a>"&gt;</span><span>
<span id="line267"></span>            </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/07/kasama02_image.jpg" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/07/kasama02_image.jpg</a>" <span class="attribute-name">alt</span>="<a class="attribute-value"></a>"&gt;</span><span>
<span id="line268"></span>          </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line269"></span>
<span id="line270"></span>          </span><span class="comment">&lt;!--コンテンツ（カラム版）ここから--&gt;</span><span>
<span id="line271"></span>          </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">contents_column</a>"&gt;</span><span>
<span id="line272"></span>                                                </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line273"></span>          </span><span class="comment">&lt;!--ゆたりの記事へのリンクボタン--&gt;</span><span>
<span id="line274"></span>
<span id="line275"></span>          </span><span class="comment">&lt;!--コンテンツここから--&gt;</span><span>
<span id="line276"></span>          </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">contents</a>"&gt;</span><span>
<span id="line277"></span>            </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">main_ttl</a>"&gt;</span><span>
<span id="line278"></span>              </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-shop/image/ttl-book_goods.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-shop/image/ttl-book_goods.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">206</a>" <span class="attribute-name">height</span>="<a class="attribute-value">84</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">BOOKandGOODS</a>"<span>/</span>&gt;</span><span>
<span id="line279"></span>            </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line280"></span>
<span id="line281"></span>            </span><span class="comment">&lt;!--レコメンドここから--&gt;</span><span>
<span id="line282"></span>            </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">recommend</a>" <span class="attribute-name">class</span>="<a class="attribute-value">fixHeight</a>"&gt;</span><span>
<span id="line283"></span>              </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">left_contents</a>"&gt;</span><span>
<span id="line284"></span>                                                                          </span><span>&lt;<span class="start-tag">table</span>&gt;</span><span>
<span id="line285"></span>                  </span><span>&lt;<span class="start-tag">tr</span>&gt;</span><span>
<span id="line286"></span>                    </span><span>&lt;<span class="start-tag">th</span>&gt;</span><span>
<span id="line287"></span>
<span id="line288"></span>                      </span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/book/post-35/" class="attribute-value">http://www.hontoyutari.com/book/post-35/</a>"&gt;</span><span>
<span id="line289"></span>                        </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">width</span>="<a class="attribute-value">200</a>" <span class="attribute-name">height</span>="<a class="attribute-value">200</a>" <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/05/kasama_no_utuwa-280x280.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/05/kasama_no_utuwa-280x280.png</a>" <span class="attribute-name">class</span>="<a class="attribute-value">attachment-200x200 size-200x200 wp-post-image</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">kasama_no_utuwa</a>" <span class="attribute-name">srcset</span>="<a class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/05/kasama_no_utuwa-280x280.png
 280w,
http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/05/kasama_no_utuwa-350x350.png
 350w,
http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/05/kasama_no_utuwa.png
 560w</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">(max-width: 200px) 100vw, 200px</a>" <span>/</span>&gt;</span><span>                      </span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line290"></span>                      </span><span>&lt;/<span class="end-tag">th</span>&gt;</span><span>
<span id="line291"></span>                    </span><span>&lt;<span class="start-tag">td</span>&gt;</span><span>
<span id="line292"></span>                      </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">category fixHeightChild_01</a>"&gt;</span><span>
<span id="line293"></span>                                              </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line294"></span>                      </span><span title="Stray end tag &quot;a&quot;." class="error">&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line295"></span>                      </span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/book/post-35/" class="attribute-value">http://www.hontoyutari.com/book/post-35/</a>"&gt;</span><span>
<span id="line296"></span>                      </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">ttl fixHeightChild_02</a>"&gt;</span><span>
<span id="line297"></span>                        かさまのうつわ                       </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line298"></span>                      </span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line299"></span>                      </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">price fixHeightChild_03</a>"&gt;</span><span>
<span id="line300"></span>                          本体価格 ￥1,200＋税                        </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line301"></span>                        </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">btn_fixHeightChild_04</a>"&gt;</span><span>
<span id="line302"></span>                                                                                  </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>='<a class="attribute-value">storesjp-button</a>' <span class="attribute-name">data-storesjp-item</span>='<a class="attribute-value">554179e93bcba972aa004a0e</a>' <span class="attribute-name">data-storesjp-variation</span>='<a class="attribute-value">554179e93bcba972aa004a0f</a>' <span class="attribute-name">data-storesjp-name</span>='<a class="attribute-value">hontoyutari</a>' <span class="attribute-name">data-storesjp-layout</span>='<a class="attribute-value">layout_c</a>' <span class="attribute-name">data-storesjp-lang</span>='<a class="attribute-value">ja</a>'&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;<span class="start-tag">script</span>&gt;</span><span>(function(d,s,id){var
 st=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return;}var
nst=d.createElement(s);nst.id=id;nst.src='http://btn.stores.jp/button.js';nst.charset='UTF-8';st.parentNode.insertBefore(nst,st);})(document,
 'script', 'storesjp-button');</span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>                                                    </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line303"></span>                      </span><span>&lt;/<span class="end-tag">td</span>&gt;</span><span>
<span id="line304"></span>                    </span><span>&lt;/<span class="end-tag">tr</span>&gt;</span><span>
<span id="line305"></span>                  </span><span>&lt;/<span class="end-tag">table</span>&gt;</span><span>
<span id="line306"></span>                                  </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line307"></span>
<span id="line308"></span>              </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">right_contents</a>"&gt;</span><span>
<span id="line309"></span>                                                              </span><span>&lt;<span class="start-tag">table</span>&gt;</span><span>
<span id="line310"></span>                  </span><span>&lt;<span class="start-tag">tr</span>&gt;</span><span>
<span id="line311"></span>                    </span><span>&lt;<span class="start-tag">th</span>&gt;</span><span>
<span id="line312"></span>
<span id="line313"></span>
<span id="line314"></span>                      </span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/book/post-158/" class="attribute-value">http://www.hontoyutari.com/book/post-158/</a>"&gt;</span><span>
<span id="line315"></span>                        </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">width</span>="<a class="attribute-value">200</a>" <span class="attribute-name">height</span>="<a class="attribute-value">200</a>" <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/03/sam-main01-1-280x280.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/03/sam-main01-1-280x280.png</a>" <span class="attribute-name">class</span>="<a class="attribute-value">attachment-200x200 size-200x200 wp-post-image</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">sam-main01</a>" <span class="attribute-name">srcset</span>="<a class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/03/sam-main01-1-280x280.png
 280w,
http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/03/sam-main01-1-350x350.png
 350w,
http://www.hontoyutari.com/wpkanri/wp-content/uploads/2016/03/sam-main01-1.png
 560w</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">(max-width: 200px) 100vw, 200px</a>" <span>/</span>&gt;</span><span>                      </span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line316"></span>                      </span><span>&lt;/<span class="end-tag">th</span>&gt;</span><span>
<span id="line317"></span>                    </span><span>&lt;<span class="start-tag">td</span>&gt;</span><span>
<span id="line318"></span>                      </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">category fixHeightChild_01</a>"&gt;</span><span>
<span id="line319"></span>                        ゆたりブックス3                      </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line320"></span>                      </span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/book/post-158/" class="attribute-value">http://www.hontoyutari.com/book/post-158/</a>"&gt;</span><span>
<span id="line321"></span>                      </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">ttl fixHeightChild_02</a>"&gt;</span><span>
<span id="line322"></span>                        いばらき</span><span>&lt;<span class="start-tag">br</span> <span>/</span>&gt;</span><span>
<span id="line323"></span>とっておきのパン屋さん                      </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line324"></span>                      </span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line325"></span>                      </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">price fixHeightChild_03</a>"&gt;</span><span>
<span id="line326"></span>                        本体価格 ￥1,200＋税                        </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line327"></span>                        </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">btn_fixHeightChild_04</a>"&gt;</span><span>
<span id="line328"></span>                                                                            </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>='<a class="attribute-value">storesjp-button</a>' <span class="attribute-name">data-storesjp-item</span>='<a class="attribute-value">55253df23cd482f1a1000599</a>' <span class="attribute-name">data-storesjp-variation</span>='<a class="attribute-value">55277790391bb3b5540006cd</a>' <span class="attribute-name">data-storesjp-name</span>='<a class="attribute-value">hontoyutari</a>' <span class="attribute-name">data-storesjp-layout</span>='<a class="attribute-value">layout_c</a>' <span class="attribute-name">data-storesjp-lang</span>='<a class="attribute-value">ja</a>'&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;<span class="start-tag">script</span>&gt;</span><span>(function(d,s,id){var
 st=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return;}var
nst=d.createElement(s);nst.id=id;nst.src='http://btn.stores.jp/button.js';nst.charset='UTF-8';st.parentNode.insertBefore(nst,st);})(document,
 'script', 'storesjp-button');</span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>                                                </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line329"></span>                      </span><span>&lt;/<span class="end-tag">td</span>&gt;</span><span>
<span id="line330"></span>                    </span><span>&lt;/<span class="end-tag">tr</span>&gt;</span><span>
<span id="line331"></span>                    </span><span>&lt;<span class="start-tag">tr</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">tr</span>&gt;</span><span>
<span id="line332"></span>                  </span><span>&lt;/<span class="end-tag">table</span>&gt;</span><span>
<span id="line333"></span>                                  </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line334"></span>
<span id="line335"></span>              </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line336"></span>            </span><span class="comment">&lt;!--レコメンドここまで--&gt;</span><span>
<span id="line337"></span>
<span id="line338"></span>            </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line339"></span>          </span><span class="comment">&lt;!--コンテンツここまで--&gt;</span><span>
<span id="line340"></span>          </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">page_top</a>"&gt;</span><span>
<span id="line341"></span>            </span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/project/entry/post-632/#wrapper" class="attribute-value">#wrapper</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span> ="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/contents/btn-page_top.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/contents/btn-page_top.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">57</a>" <span class="attribute-name">height</span>="<a class="attribute-value">57</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">PAGE TOP</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line342"></span>            </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line343"></span>          </span><span>&lt;/<span class="end-tag">section</span>&gt;</span><span>
<span id="line344"></span>        </span><span>&lt;/<span class="end-tag">article</span>&gt;</span><span>
<span id="line345"></span>      </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line346"></span>  </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line347"></span>  </span><span class="comment">&lt;!--メインここまで--&gt;</span><span>
<span id="line348"></span>
<span id="line349"></span>  </span><span class="comment">&lt;!--フッターここから--&gt;</span><span>
<span id="line350"></span>  </span><span>&lt;<span class="start-tag">footer</span>&gt;</span><span>
<span id="line351"></span>  </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">footer_nav</a>"&gt;</span><span>
<span id="line352"></span>    </span><span>&lt;<span class="start-tag">table</span>&gt;</span><span>
<span id="line353"></span>      </span><span>&lt;<span class="start-tag">tr</span>&gt;</span><span>
<span id="line354"></span>        </span><span>&lt;<span class="start-tag">td</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/book/" class="attribute-value">http://www.hontoyutari.com/book/</a>"&gt;</span><span>
<span id="line355"></span>          </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-book_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-book_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">48</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">BOOK</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">td</span>&gt;</span><span>
<span id="line356"></span>        </span><span>&lt;<span class="start-tag">td</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/goods/" class="attribute-value">http://www.hontoyutari.com/goods/</a>"&gt;</span><span>
<span id="line357"></span>          </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-goods_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-goods_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">59</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">GOODS</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">td</span>&gt;</span><span>
<span id="line358"></span>        </span><span>&lt;<span class="start-tag">td</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/project/" class="attribute-value">http://www.hontoyutari.com/project/</a>"&gt;</span><span>
<span id="line359"></span>          </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-project_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-project_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">78</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">PROJECT</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">td</span>&gt;</span><span>
<span id="line360"></span>        </span><span>&lt;<span class="start-tag">td</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/shop/" class="attribute-value">http://www.hontoyutari.com/shop/</a>"&gt;</span><span>
<span id="line361"></span>          </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-shop_list_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-shop_list_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">96</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">SHOP LIST</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">td</span>&gt;</span><span>
<span id="line362"></span>        </span><span>&lt;<span class="start-tag">td</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/about/" class="attribute-value">http://www.hontoyutari.com/about/</a>"&gt;</span><span>
<span id="line363"></span>          </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-about_us_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-about_us_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">91</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">ABOUT US</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">td</span>&gt;</span><span>
<span id="line364"></span>        </span><span>&lt;<span class="start-tag">td</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/info/" class="attribute-value">http://www.hontoyutari.com/info/</a>"&gt;</span><span>
<span id="line365"></span>          </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-information_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-information_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">122</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">INFORMATION</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">td</span>&gt;</span><span>
<span id="line366"></span>        </span><span>&lt;<span class="start-tag">td</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a href="view-source:http://www.hontoyutari.com/contact/" class="attribute-value">http://www.hontoyutari.com/contact/</a>"&gt;</span><span>
<span id="line367"></span>          </span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">src</span>="<a href="view-source:http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-contact_off.png" class="attribute-value">http://www.hontoyutari.com/wpkanri/wp-content/themes/hontoyutari/data-common/image/footer/nav-contact_off.png</a>" <span class="attribute-name">width</span>="<a class="attribute-value">81</a>" <span class="attribute-name">height</span>="<a class="attribute-value">26</a>" <span class="attribute-name">alt</span>="<a class="attribute-value">CONTACT</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">td</span>&gt;</span><span>
<span id="line368"></span>      </span><span>&lt;/<span class="end-tag">tr</span>&gt;</span><span>
<span id="line369"></span>    </span><span>&lt;/<span class="end-tag">table</span>&gt;</span><span>
<span id="line370"></span>  </span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line371"></span></span><span>&lt;/<span class="end-tag">footer</span>&gt;</span><span>
<span id="line372"></span>  </span><span class="comment">&lt;!--フッターここまで--&gt;</span><span>
<span id="line373"></span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line374"></span></span><span class="comment">&lt;!--コンテナーここまで--&gt;</span><span>
<span id="line375"></span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line376"></span></span><span class="comment">&lt;!--ラッパーここまで--&gt;</span><span>
<span id="line377"></span>
<span id="line378"></span></span><span>&lt;/<span class="end-tag">body</span>&gt;</span><span>
<span id="line379"></span></span><span>&lt;/<span class="end-tag">html</span>&gt;</span><span>
<span id="line380"></span></span></pre><menu id="actions" type="context"><menuitem accesskey="L" label="指定行へ移動..." id="goToLine"></menuitem><menuitem checked="true" type="checkbox" label="長い行を折り返す" id="wrapLongLines"></menuitem><menuitem checked="true" type="checkbox" label="構文を強調表示" id="highlightSyntax"></menuitem></menu></body></html>
